apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: readi
spec:
  selector:
    matchLabels:
      app: readi
  replicas: 1
  template:
    metadata:
      labels:
        app: readi
    spec:
      containers:
      - name: readi
        image: nginx 
        ports:
        - containerPort: 80
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until wget 10.107.168.197:80; do echo waiting for myservice; sleep 2; done;']

